[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageDirectory = "coverage"
coveragePathIgnorePatterns = ["**/test-utils/setup.ts"]
coverageThreshold = {
  global = {
    lines = 80,
    functions = 80,
    branches = 80,
    statements = 80
  }
}